server:
  port: 10087
  servlet:
    context-path: /bemServer
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://titan:df6100@127.0.0.1:7777/eureka/
      #defaultZone: http://10.1.0.192:7777/eureka/
spring:
  application:
    name: bem-server
  datasource:
#    master:
      url: jdbc:mysql://172.21.29.203:3306/titan-bem?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: df6100
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 获取连接等待超时的时间queryHistoricTask
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat, wall
      # 打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
#    cluster:
#    - key: slave1
#      url: jdbc:mysql://172.21.29.55:3306/titan-cim?serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
#      username: root
#      password: df6100
#      driver-class-name: com.mysql.jdbc.Driver
#      type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # activiti default configuration
  activiti:
    database-schema-update: true
    #自动部署开关  有bug 改一个文件 也会全部重新部署
    check-process-definitions: true
    #自动扫描路径
    process-definition-location-prefix: classpath:/processes/
    #    process-definition-location-suffixes:
    #      - **.bpmn
    #      - **.bpmn20.xml
    #历史数据保存级别 none activity audit full
    #history-level: full
    #asyncExectorActivate是指activiti在流程引擎启动时激活AsyncExecutor,异步:true-开启,false-关闭
    async-executor-activate: false

mybatis:
  typeAliasesPackage: classpath*:com/bem/domain
  mapperLocations: classpath*:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml

mapper:
  #公用接口类路径
  mappers: com.bem.baseMapper.BemBaseMapper
  identity: MYSQL

logging:
  level:
    com.bem: DEBUG
    org.springframework.web: DEBUG
  path: log
  #日志最大保存的数量 一般一天生成一个日志
  #file:
    #max-history: 60

pagehelper:
  helper-dialect: MYSQL
  params: count=countSql
  reasonable: false
  support-methods-arguments: true





